### ISSUE TITLE
ci の設定に lint を追加

### ISSUE THREAD

**Issue by mikuni392** [topgate/goutils#11]
ci に golangci-lint を導入

**Comment by mikuni392** [comment]
golangici-lint もそうなのですが、go の lint は何を行えばよいのでしょうか？
https://github.com/golangci/golangci-lint#supported-linters

**Comment by mikuni392** [comment]
@tgoikawa 
golnagci-lint の下記のものを実行しようかなと思っていますが、いかがでしょうか？
format するものは build などを行わないため要らないかと思いました。

- govet（引数がフォーマットと一致しない printf を報告）
- errcheck（error をチェックしていないコードを報告）
- golint（format せずに format されていないコードを報告）
- unparam（使用されていない関数の値を報告）
- prealloc（事前に割り当てられる可能性のあるスライスを報告）

**Comment by tgoikawa** [comment]
navilinkで使ってたものも入れてください
> format するものは build などを行わないため要らないかと思いました。

もともとformatはしてないです。formatされてるかのチェックはしてますが

- goimports (コードがgoimportsでフォーマットされてるかチェック)
- errcheck (errorが無視されていないかチェック)
- misspell (綴が間違えていないかチェック)
- staticcheck (静的解析する内容が増やせるっぽい)

**Comment by tgoikawa** [comment]
いや、goimports指定するとformat自体はされるか。
ともかくformatをする目的としては使ってないです。あくまでもコードのチェックが目的

**Comment by mikuni392** [comment]
承知致しました。それでは下記の lint で PR 作成します

- govet（引数がフォーマットと一致しない printf を報告）
- golint（format せずに format されていないコードを報告）
- unparam（使用されていない関数の値を報告）
- prealloc（事前に割り当てられる可能性のあるスライスを報告）
- **goimports (コードがgoimportsでフォーマットされてるかチェック)**
- **misspell (綴が間違えていないかチェック)**
- **staticcheck (静的解析する内容が増やせるっぽい)**
- **errcheck（error をチェックしていないコードを報告）**

**Comment by mikuni392** [comment]
uncovert （不要な型変換）も抜けていたため追加します
