### ISSUE TITLE
GoDoc対応したい

### ISSUE THREAD

**Issue by tgoikawa** [topgate/goutils#19]
GoDocでソースコード中のコメントがドキュメントとして出力できるようにしたい

**Comment by ryutah** [comment]
https://godoc.org/github.com/topgate/goutils
はい

**Comment by ryutah** [comment]
ああなんかトップレベルは出てるけど、コードのコメントとかは出てないのか

**Comment by tgoikawa** [comment]
そうそう

**Comment by tgoikawa** [comment]
ていうか自動でGoDocで参照できるのか。
READMEにリンク貼っておきたいですね

**Comment by ryutah** [comment]
バッジつけよ！

https://qiita.com/shibukawa/items/8c70fdd1972fad76a5ce#%E3%81%8A%E3%81%BE%E3%81%91

**Comment by tgoikawa** [comment]
close忘れ
