### ISSUE TITLE
ユニットテストのサブテストの数だけログが出力されてしまう

### ISSUE THREAD

**Issue by shigwata** [topgate/goutils#34]
ユニットテストのサブテストの数だけログが出力されてしまうため削除してもらいたい

https://github.com/topgate/goutils/blob/3464d19874cd4f4b622753bfc8c6562853226505/gcp/appengine/log/log.go#L110

**Comment by ryutah** [comment]
@shigwata 修正した！

**Comment by shigwata** [comment]
ありがとうございます！
