### ISSUE TITLE
sql.DB用のRunInTransactionが欲しい。

### ISSUE THREAD

**Issue by tgoikawa** [topgate/goutils#47]
こんな感じのシグネチャで無名関数内でSQL実行してエラー返したらロールバック、nil返したらコミットするsql.DBの補助関数がほしい
```go
func RunInTransaction(db *sql.DB,f func(tx *sql.Tx)error) error {...
```

**Comment by tgoikawa** [comment]
ぐぐったら類似機能もったライブラリあったりしないだろうか

**Comment by tgoikawa** [comment]
パッケージ名どうしよう。sqlだとsqlライブラリとかぶるし・・・
sqldbにする？

**Comment by tgoikawa** [comment]
@ryutah 意見ほしい

**Comment by ryutah** [comment]
`sqls` ？

**Comment by tgoikawa** [comment]
goのパッケージであまり複数形にする印象がないのでとりあえずsqldbにして実装してみた

**Comment by tgoikawa** [comment]
割と複数形が使われているなら sqlsにしてもいいかも？
