### ISSUE TITLE
pubsubメッセージからGCSイベントをパースする処理を実装する

### ISSUE THREAD

**Issue by tgoikawa** [topgate/goutils#58]
pubsubメッセージからGCSイベントをパースするシーンはよくあるので、これを実装する

**Comment by ryutah** [comment]
[functions framework](https://github.com/GoogleCloudPlatform/functions-framework-go)の利用前提にするイメージ？

**Comment by tgoikawa** [comment]
いや、google.golang.org/api/pubsub/v1のReceivedMessageからGCSEventをパースする予定です。
ただこれだとメッセージのデータが実際にGCSEventじゃなかったとしても成功しちゃうんですよね・・・GCSのEventだって確かに判定出来るような情報もなさそうだし。
これは共通ライブラリ化せずに各自で実装してねって方向にしたほうがいいかも

**Comment by ryutah** [comment]
あーたしかにちょっと微妙かもなあ

**Comment by tgoikawa** [comment]
これはいったんcloseしますね
