### ISSUE TITLE
ログレベルを設定できるようにしたい

### ISSUE THREAD

**Issue by k-tky** [topgate/goutils#59]
ログ出力レベルを環境変数etcで設定してレベルに応じて出力の要否を制御したい

https://github.com/topgate/goutils/blob/master/gcp/appengine/log/log.go

**Comment by ryutah** [comment]
いります？ 🤔 

オンプレとかならストレージ容量問題とかあるので対策必要だったりしますけど、Cloud Loggingだとそのあたりって気にしなくていいですし、基本全部出して置いたほうがバグの調査とかが捗ると思う。

あとあり得るとしたらパフォーマンス的な問題。。。？

**Comment by tgoikawa** [comment]
なぜ欲しいのかという理由は書いてほしいですね。その上でそのやりたいことをこのライブラリで面倒を見るべきか議論を行いたいです。

**Comment by k-tky** [comment]
Debugログがですぎると、ログが汚れるかと思いましたが、

>オンプレとかならストレージ容量問題とかあるので対策必要だったりしますけど、Cloud Loggingだとそのあたりって気にしなくていいですし、基本全部出して置いたほうがバグの調査とかが捗ると思う。

との指摘でフィルタなんか使えば除外もできるし、不要だなと思いましたので取り下げます。

>なぜ欲しいのかという理由は書いてほしいですね。

今後、この点は記載します。（指摘ありがとうございます）
