### ISSUE TITLE
CircleCIのImage設定に、DockerHub認証情報を追加する

### ISSUE THREAD

**Issue by ryutah** [topgate/goutils#60]
[11/1よりDockerHubにPullリクエスト制限](https://docs.docker.com/docker-hub/download-rate-limit/)がつくことになってしまう、それ以降でCIがコケる可能性が浮上したため、対応が必要となった。

## Todo

- CircleCIのイメージ設定で、DockerHubの認証を追加する

**Comment by taka0024-topgate** [comment]
@tgoikawa これ手が空いたら着手して貰いたい

**Comment by tgoikawa** [comment]
これCircleCIの環境変数設定でDOCKERHUB_USERとDOCKERHUB_PASSWORDの設定必要なんですかね

**Comment by taka0024-topgate** [comment]
それと別にDockerHubにログインするリクエストが必要なのでは？

**Comment by ryutah** [comment]
いらない。

TopgateのOrgのContext設定でそのあたりの環境変数が使えるように設定済みなので、contextを利用できるように宣言を追加しつつauth周りの設定を追加すればOK。

**Comment by tgoikawa** [comment]
Orgで設定済みなのね。OKです
